export const major = [
    "Computer and information sciences",
    "Psychology",
    "Biology/biological sciences",
    "Information science/studies",
    "Economics",
    "Finance",
    "Kinesiology and exercise science",
    "Registered nursing/registered nurse",
    "Speech communication and rhetoric",
    "Human resources management/personnel administration",
    "Public health",
    "Logistics, materials, and supply chain management",
    "Electrical and electronics engineering",
    "Criminal justice/safety studies",
    "Management science",
    "Political science and government",
    "Mechanical engineering",
    "Labor and industrial relations",
    "Accounting",
    "Cell/cellular biology and histology",
    "Mathematics",
    "Health services administration",
    "Marketing/marketing management",
    "Journalism",
    "English language and literature",
    "Animal sciences",
    "Bioengineering and biomedical engineering",
    "History",
    "Civil engineering",
    "Sport and fitness administration/management",
    "Chemical engineering",
    "Statistics",
    "Nutrition sciences",
    "Social work",
    "Industrial engineering",
    "Molecular genetics",
    "Aerospace, aeronautical and astronautical/space engineering",
    "Philosophy",
    "Engineering science",
    "Cognitive science",
    "Physics",
    "Chemistry",
    "Music performance",
    "Design and visual communications",
    "Art/art studies",
    "Food science",
    "Social sciences",
    "Drama and dramatics/theatre arts",
    "Environmental studies",
    "Linguistics",
    "Biotechnology",
    "Ceramic sciences and engineering",
    "Clinical/medical laboratory science and allied professions",
    "Natural resources management and policy",
    "Health services/allied health/health sciences",
    "Allied health diagnostic, intervention, and treatment professions",
    "Rehabilitation and therapeutic professions",
    "Sociology",
    "Dance",
    "Environmental science",
    "Public policy analysis",
    "Microbiology",
    "Anthropology",
    "Business administration and management",
    "Molecular biology",
    "Biochemistry",
    "Marine biology and biological oceanography",
    "City/urban, community and regional planning",
    "Landscape architecture",
    "Agricultural engineering",
    "Geography",
    "Art history, criticism and conservation",
    "Plant sciences",
    "Astrophysics",
    "Film/cinema/video studies",
    "Cinematography and film/video production",
    "Agriculture",
    "Health information/medical records administration/administrator",
    "Women's studies",
    "Spanish language and literature",
    "American/united states studies/civilization",
    "Biometry/biometrics",
    "Geology/earth science",
    "Environmental design/architecture",
    "African-american/black studies",
    "Urban studies/affairs",
    "Chinese language and literature",
    "German language and literature",
    "Classics and classical languages, literatures, and linguistics",
    "Entomology",
    "Religion/religious studies",
    "East asian studies",
    "Italian language and literature",
    "Music",
    "Health/health care administration/management",
    "Comparative literature",
    "Japanese language and literature",
    "Korean language and literature",
    "French language and literature",
    "Meteorology"
];  